title: Intergalactic Society Blog
description: A fictional newsletter from the stars.
baseurl: "/Intergalactic-Society-Blog" # repo name
url: "https://karlknopf.github.io"
theme: minima

# Enable future-dated posts if needed
future: true

# Markdown processor
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:year/:month/:day/:title.html
